#!/usr/bin/env python3
"""beta4-build.py — single source of truth for the "The Wake" (beta4) page chrome.

Every beta4 page is generated by wrapping its unique body in ONE canonical chrome
(head metas, favicon, theme-color, canonical, OG/Twitter, skip link, nav, optional
breadcrumb, footer). Run it to (re)build all pages so they cannot drift apart.

It reuses each page's existing unique <body> content (from the content marker up to
<footer>) and its JSON-LD + ai-summary, and replaces all shared chrome.

    python3 tools/beta4-build.py
"""
import re, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
B = "https://cruisinginthewake.com"
DATE = "2026-06-07"

SDG = ('<!--\nSoli Deo Gloria\nAll work on this project is offered as a gift to God.\n'
       '"Trust in the LORD with all your heart..." — Proverbs 3:5\n'
       '"Whatever you do, work heartily..." — Colossians 3:23\n-->')

NAV = "\n".join([
    '  <nav class="nav" aria-label="Main">',
    '    <span class="name serif">In the Wake</span>',
    f'    <a href="{B}/ships/">Ships</a>',
    f'    <a href="{B}/ports.html">Ports</a>',
    f'    <a href="{B}/cruise-lines/">Cruise Lines</a>',
    f'    <a href="{B}/restaurants/">Restaurants</a>',
    f'    <a href="{B}/articles.html">Articles</a>',
    f'    <a href="{B}/planning.html">Tools</a>',
    f'    <a href="{B}/accessibility.html">Accessibility</a>',
    '  </nav>',
])

FOOTER = ('  <footer>In the Wake &middot; honest, calm, concrete cruise planning '
          '&middot; no ads, independent of cruise lines &middot; Soli Deo Gloria</footer>')

OG_IMAGE = f"{B}/assets/beta/wake-hero-1280.webp"
PRELOAD = ('<link rel="preload" as="image" href="/assets/beta/wake-hero-1280.webp" '
           'imagesrcset="/assets/beta/wake-hero-800.webp 800w, /assets/beta/wake-hero-1280.webp 1280w" '
           'imagesizes="100vw"/>')

# Per-page: canonical title + breadcrumb trail (None = homepage, no breadcrumb)
PAGES = {
    "indexbeta4.html":   ("In the Wake — cruise planning", None),
    "contentbeta4.html": ("From the back of the boat — In the Wake",
                          [("Home", f"{B}/"), ("Articles", f"{B}/articles.html"), ("From the back of the boat", None)]),
    "authorbeta4.html":  ("Ken Baker — Founder & Editor — In the Wake",
                          [("Home", f"{B}/"), ("About", f"{B}/about-us.html"), ("Ken Baker", None)]),
    "articlebeta4.html": ("Cruise Cabin Organization: Making Small Spaces Work — In the Wake",
                          [("Home", f"{B}/"), ("Articles", f"{B}/articles.html"), ("Cabin Organization", None)]),
    "shiphubbeta4.html": ("Ships — In the Wake",
                          [("Home", f"{B}/"), ("Ships", None)]),
}


def crumbs_html(trail):
    items = [f'<a href="{h}">{l}</a>' if h else f'<span aria-current="page">{l}</span>' for l, h in trail]
    return '\n\n  <nav class="crumbs" aria-label="Breadcrumb">\n    ' + ' &rsaquo;\n    '.join(items) + '\n  </nav>'


def build(fname, title, trail):
    src = (ROOT / fname).read_text(encoding="utf-8")
    summ = re.search(r'name="ai-summary" content="(.*?)"', src, re.S).group(1)
    ld = re.search(r'(<script type="application/ld\+json">.*?</script>)', src, re.S).group(1)
    body = re.search(r'\n(  <(?:main id="main"|article class="content-hero")>.*?)\n  <footer', src, re.S).group(1)
    canonical = f"{B}/{fname}"
    crumb = crumbs_html(trail) if trail else ""
    out = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
{SDG}
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<meta name="robots" content="noindex"/>
<link rel="icon" href="/favicon.ico"/>
<link rel="apple-touch-icon" href="/apple-touch-icon.png"/>
<meta name="theme-color" content="#0e6e8e"/>
<link rel="canonical" href="{canonical}"/>
<title>{title}</title>
<meta name="ai-summary" content="{summ}"/>
<meta name="last-reviewed" content="{DATE}"/>
<meta name="content-protocol" content="ICP-2"/>
<meta property="og:title" content="{title}"/>
<meta property="og:description" content="{summ}"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="{canonical}"/>
<meta property="og:image" content="{OG_IMAGE}"/>
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:title" content="{title}"/>
<meta name="twitter:image" content="{OG_IMAGE}"/>
{PRELOAD}
<link rel="stylesheet" href="/stylesbeta4.css?v=beta4"/>
{ld}
</head>
<body>

  <a href="#main" class="skip-link">Skip to main content</a>

{NAV}{crumb}

{body}

{FOOTER}
</body>
</html>
"""
    out_dir = ROOT / "tools" / "_beta4-build"
    out_dir.mkdir(exist_ok=True)
    (out_dir / fname).write_text(out, encoding="utf-8")
    print("built (scratch)", out_dir / fname)


if __name__ == "__main__":
    for fname, (title, trail) in PAGES.items():
        build(fname, title, trail)
