#!/usr/bin/env node
/**
 * generate-index.cjs — Regenerate the rule index in README.md.
 *
 * Scans rules/ directory, builds a sortable table grouped by family,
 * and substitutes the block between <!-- RULE-INDEX-START --> and
 * <!-- RULE-INDEX-END --> in README.md.
 *
 * Usage:
 *   node admin/validator-spec/scripts/generate-index.cjs         # write
 *   node admin/validator-spec/scripts/generate-index.cjs --check # diff only, exit 1 if changes
 *
 * Soli Deo Gloria.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const SPEC_ROOT = path.resolve(__dirname, '..');
const RULES_DIR = path.join(SPEC_ROOT, 'rules');
const README = path.join(SPEC_ROOT, 'README.md');
const CHECK_ONLY = process.argv.includes('--check');

function parseFrontMatter(text) {
  const lines = text.split('\n');
  if (lines[0] !== '---') return null;
  let end = -1;
  for (let i = 1; i < lines.length; i++) if (lines[i] === '---') { end = i; break; }
  if (end === -1) return null;
  const fm = {};
  for (let i = 1; i < end; i++) {
    const m = lines[i].match(/^([a-zA-Z][\w-]*):\s*(.*)$/);
    if (!m) continue;
    const val = m[2].trim();
    if (val) fm[m[1]] = val.replace(/^["']|["']$/g, '');
  }
  return fm;
}

function familyOf(id) {
  return id.split('-')[0];
}

function main() {
  if (!fs.existsSync(RULES_DIR)) {
    console.error(`rules directory not found: ${RULES_DIR}`);
    process.exit(1);
  }

  const ruleFiles = fs.readdirSync(RULES_DIR).filter((f) => f.endsWith('.md')).sort();
  const rules = [];
  for (const f of ruleFiles) {
    const text = fs.readFileSync(path.join(RULES_DIR, f), 'utf8');
    const fm = parseFrontMatter(text);
    if (!fm || !fm.id) continue;
    rules.push({
      id: fm.id,
      name: fm.name || '',
      severity: fm.severity || '',
      provenance: fm.provenance || '',
      status: fm.status || '',
      file: `rules/${f}`,
    });
  }

  // Group by family
  const byFamily = {};
  for (const r of rules) {
    const fam = familyOf(r.id);
    if (!byFamily[fam]) byFamily[fam] = [];
    byFamily[fam].push(r);
  }
  for (const fam in byFamily) {
    byFamily[fam].sort((a, b) => a.id.localeCompare(b.id));
  }

  // Render
  const lines = [];
  lines.push(`**Total rules:** ${rules.length}  |  Generated by \`scripts/generate-index.cjs\`\n`);
  const families = Object.keys(byFamily).sort();
  for (const fam of families) {
    lines.push(`### ${fam} (${byFamily[fam].length})\n`);
    lines.push(`| ID | Name | Severity | Provenance | Status |`);
    lines.push(`|---|---|---|---|---|`);
    for (const r of byFamily[fam]) {
      lines.push(`| [\`${r.id}\`](${r.file}) | ${r.name} | ${r.severity} | ${r.provenance} | ${r.status} |`);
    }
    lines.push(``);
  }

  const newBlock = lines.join('\n');
  const existing = fs.readFileSync(README, 'utf8');
  const updated = existing.replace(
    /<!-- RULE-INDEX-START -->[\s\S]*?<!-- RULE-INDEX-END -->/,
    `<!-- RULE-INDEX-START -->\n${newBlock}\n<!-- RULE-INDEX-END -->`
  );

  if (updated === existing) {
    console.log(`README.md already up to date (${rules.length} rule(s) indexed).`);
    process.exit(0);
  }

  if (CHECK_ONLY) {
    console.log(`README.md is STALE. Run generate-index.cjs without --check to update.`);
    process.exit(1);
  }

  fs.writeFileSync(README, updated, 'utf8');
  console.log(`README.md regenerated with ${rules.length} rule(s) across ${families.length} familie(s).`);
}

main();
